<div class="container-max container-top">
    <div class="content-container">
        <div class="content-top__wrap">
            <div class="content-top">
                <div class="content-top1">cctv & security systems</div>
                <div class="content-top2">Highly experienced in security design, instalation & servicing</div>
                <a href="#" class="content-top3">Read more</a>
            </div>
        </div>
    </div>
</div>
<div class="container-max container-mid__wrap">
    <div class="content-container">
        <div class="container-mid">
            <div class="container-mid__left">
                <div class="container-mid__left__top__wrap">
                    <div class="container-mid__left__top__ico"></div>
                    <div class="container-mid__left__top__txt__wrap">
                        <p class="container-mid__left__top__txt1">
                            <span class="container-mid__left__top__txt1_blue">our</span> services
                        </p>
                        <p class="container-mid__left__top__txt2">
                            High quality of products
                        </p>
                    </div>
                </div>
                <div class="container-mid__left__mid__wrap">
                    <p class="container-mid__left__mid">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
                    </p>
                </div>
                <div class="container-mid__left__bot__wrap">
                    <p class="container-mid__left__bot">
                        workng since 2001
                    </p>
                </div>
            </div>
            <div class="container-mid__right1">
                <div class="container-mid__right__wrap container-mid__right__top__wrap1">
                    <div class="container-mid__right__ico__wrap">
                        <div class="container-mid__right__ico"></div>
                    </div>
                    <div class="container-mid__right__txt__wrap">
                        <div class="container-mid__right__txt1">
                            SMART Systems
                        </div>
                        <div class="container-mid__right__txt2">
                            Our SMART Systems takes peace of mind to a whole new level. This Technology was born out of our passion to go far beyond just good customer service.
                        </div>
                    </div>
                </div>
                <div class="container-mid__right__wrap container-mid__right__top__wrap1">
                    <div class="container-mid__right__ico__wrap">
                        <div class="container-mid__right__ico"></div>
                    </div>
                    <div class="container-mid__right__txt__wrap">
                        <div class="container-mid__right__txt1">
                            SMART Systems
                        </div>
                        <div class="container-mid__right__txt2">
                            Our SMART Systems takes peace of mind to a whole new level. This Technology was born out of our passion to go far beyond just good customer service.
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-mid__right2">
                <div class="container-mid__right__wrap container-mid__right__top__wrap1">
                    <div class="container-mid__right__ico__wrap">
                        <div class="container-mid__right__ico"></div>
                    </div>
                    <div class="container-mid__right__txt__wrap">
                        <div class="container-mid__right__txt1">
                            SMART Systems
                        </div>
                        <div class="container-mid__right__txt2">
                            Our SMART Systems takes peace of mind to a whole new level. This Technology was born out of our passion to go far beyond just good customer service.
                        </div>
                    </div>
                </div>
                <div class="container-mid__right__wrap container-mid__right__top__wrap1">
                    <div class="container-mid__right__ico__wrap">
                        <div class="container-mid__right__ico"></div>
                    </div>
                    <div class="container-mid__right__txt__wrap">
                        <div class="container-mid__right__txt1">
                            SMART Systems
                        </div>
                        <div class="container-mid__right__txt2">
                            Our SMART Systems takes peace of mind to a whole new level. This Technology was born out of our passion to go far beyond just good customer service.
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>