<div class="container-max container-top">
    <div class="content-container">
        <div class="content-top__wrap">
            <div class="content-top">
                <div class="content-top1">cctv & security systems</div>
                <div class="content-top2">Highly experienced in security design, instalation & servicing</div>
                <a href="#" class="content-top3">Read more</a>
            </div>
        </div>
    </div>
</div>
